### ISSUE TITLE
Authentification trouble

### ISSUE THREAD

**Issue by Celli119** [usineur/go-debrid#1]
Impossible to login while trying:

``` bash
go-debrid --debrid
```

**Comment by usineur** [comment]
option`"--debrid"` works with an extra argument, a link to a website supported by Alldebrid, for example:
`./go-debrid --debrid http://www.uptobox.com/FAKE`

It will ask you for your credentials, the first time you execute it

**Comment by Celli119** [comment]
Yes, of course, that's what I did but each time I enter my login and password, there are asked to me again. Would it be possible there is any trouble with uppercase ?

**Comment by usineur** [comment]
Oh ok, my bad.
Try to remove this file: `~/.config/alldebrid/cookie.txt
`
Then try to connect again.

**Comment by Celli119** [comment]
OK, that finaly works, the issue was go-debrid didn't have access to write into this folder.
