### ISSUE TITLE
[Feature] Credential support

### ISSUE THREAD

**Issue by link-webcreations** [usineur/go-debrid#2]
Hello,

I have successfully compile your amazing tool, just wanna know how to get connected with alldebrid services. Is your tool support it ?

I have try this :)

<pre>
$ go-debrid -l
GetTableDataAsArrayWithHeaders helper: No results for XPATH //table[@id="torrent"]
</pre>

BR

**Comment by usineur** [comment]
Hi,

check if you have something in ~/.config/alldebrid. You may have a file named "cookie.txt".
Normally, this file contains an "uid" entry. If not, try to remove this file and relaunch go-debrid.
It should ask your credentials again.

**Comment by usineur** [comment]
Hi,

it seems to come from Alldebrid. The site redirects the url without "www".

Just apply this patch:
`diff --git a/alldebrid/core.go b/alldebrid/core.go
index 70401c4..6fe572e 100644
--- a/alldebrid/core.go
+++ b/alldebrid/core.go
@@ -12,7 +12,7 @@ import (
     "strings"
 )
 
-const host = "https://www.alldebrid.com"
+const host = "https://alldebrid.com"
`

Then recompile. It should work.

**Comment by usineur** [comment]
Hi,

it seems that it comes from AllDebrid. The site redirects the url without "www".

Fix in commit 4e172811325761dc4ab8a5b063bb58f46612801a

**Comment by link-webcreations** [comment]
It works fine ! Thanks
