### ISSUE TITLE
Ajout de torrent

### ISSUE THREAD

**Issue by Naboris** [usineur/go-debrid#3]
L'ajout de torrent ne fonctionne sur windows
![issue](https://cloud.githubusercontent.com/assets/13244499/13760500/bdb7e4c8-ea33-11e5-934f-2dd4f92310cb.PNG)

**Comment by usineur** [comment]
C'est une régression présente aussi sous Linux. Merci pour le retour.

Résolue au commit 5fa4306

Je vais fournir une nouvelle release du coup :+1:

**Comment by gonzo-oin** [comment]
J'ai l'impression que le problème est revenu sur Mac OS.

**Comment by usineur** [comment]
Les API ont changées. Visiblement, ils ont mis en place l'upload multiple de torrents. Ce n'est pas un problème liée à l'OS utilisé.

Je tenterai de fixer ça dès que je trouve un peu de temps.

**Comment by usineur** [comment]
@gonzo-oin c'est bon, c'est corrigé. Voir commits 49d33c149f3792fcc67b51927e37a279126799f5 9e34439829e205a4f440d0826344f49ebaee7a84 et 57f153abbb9dfd24a1a9d028ee56ad89306e4c4e
