### ISSUE TITLE
Torrent : invalid cookie

### ISSUE THREAD

**Issue by Naboris** [usineur/go-debrid#4]
J'ai essayé de supprimer le cookie.txt pour résoudre le problème mais sans succès.

![issue2](https://cloud.githubusercontent.com/assets/13244499/13772907/e9492f44-ea96-11e5-8f5f-d931c048ea24.PNG)

**Comment by usineur** [comment]
Cette fois, seule la version Windows est touchée. Je regarde.

**Comment by usineur** [comment]
Fix rapide: `dos2unix cookie.txt` ou conversion EOL Windows -> Unix avec Notepad++

**Comment by Naboris** [comment]
Tout fonctionne normalement merci.

**Comment by usineur** [comment]
Super. Je ferme.
