### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Amonbofils** [usineur/go-debrid#5]
Bonjour,

Tout d'abord merci pour ton taff !

Je viens pour un coup de main, je ne suis pas un habitué de go, donc je tatonne un peu ...

Je viens de faire l'install de goland, mais quand je lance la cmd :

[code]go get github.com/usineur/go-debrid[/code]

j'obtiens ceci :

[code]src/github.com/usineur/goch/helper.go:27: function ends without a return statement
src/github.com/usineur/goch/helper.go:43: function ends without a return statement
src/github.com/usineur/goch/helper.go:51: function ends without a return statement
src/github.com/usineur/goch/helper.go:66: function ends without a return statement
src/github.com/usineur/goch/helper.go:99: function ends without a return statement
src/github.com/usineur/goch/helper.go:140: function ends without a return statement
src/github.com/usineur/goch/helper.go:178: function ends without a return statement
[/code]

aurais-tu une idée ?

Merci d'avance !

**Comment by usineur** [comment]
Salut,

là comme ça non... Ça compile bien chez moi, quelle version de go utilises-tu ? Tu es sur quel environnement (win, linux, ...) ?

**Comment by Amonbofils** [comment]
Je suis sur debian wheezy. J'ai pris la version distribué de goland...

J'ai suivi le tutoriel d'installation sur leur site.
Le 14 juin 2016 8:50 PM, "Matthieu Milan" notifications@github.com a
écrit :

**Comment by usineur** [comment]
un petit `go version` dans un terminal dans le doute... Pour savoir quelle version précise de Golan**g** est installée ;)

Je ne suis pas sous Debian.

**Comment by usineur** [comment]
ah ouais, si j'en crois cette page [Golang Debian Wheezy](https://packages.debian.org/fr/wheezy/golang-go), tu dois avoir la version 1.0.2

Elle est dépassée, tu dois trouver un moyen d'upgrader en version 1.5 ou +

**Comment by usineur** [comment]
A moins que je ne sache vraiment pas lire que tu as bel et bien la version 1.6.2 depuis le site officiel... Et il ne me restera qu'à tester avec cette dernière...

**Comment by Amonbofils** [comment]
Je vais voir des que j'aurais mon pc entre les mains et je te redis
Le 14 juin 2016 9:18 PM, "Matthieu Milan" notifications@github.com a
écrit :

**Comment by Amonbofils** [comment]
go version go1.0.2

faut que je trouve ou et comment updater go ... je vais m'atteler la
dessus, et je reviens vers toi si jamais je rencore d'autres soucis ou que
ce n'est pas résolue !

Merci encore d'avoir pris de ton temps pour m'aider !

**Comment by Amonbofils** [comment]
Alors y'a du mieux !
- Version 1.6.2 OK
- la ligne go get github.com/usineur/go-debrid est passée

mais apres quoi faire ? Quand je tape :

root@Maison:/tmp/go/bin# go-debrid -l
-bash: go-debrid : commande introuvable

y'aurai-t-il des subtilités non saisies ?

**Comment by usineur** [comment]
Il faut que tu cherches l'endroit où a été compilé go-debrid. il est normalement dans $GOPATH/bin
et de là il faut taper `./go-debrid -l` par exemple

Tu pourras rentrer tes identifiants et c'est parti

Ensuite si tu veux lancer de n'importe où, il faudra l'ajouter à ton PATH.

Je te laisse trouver tout ça sur le web.

**Comment by Amonbofils** [comment]
Je m'auto réponds ..

la commande est ./go-debrid et non pas juste go-debrid ...

**Comment by usineur** [comment]
en effet ;-)

**Comment by Amonbofils** [comment]
merci encore !

je vais chercher pour cette histoire de path ...

**Comment by Amonbofils** [comment]
humm ... désolé mais j'ai encore un soucis 

Lors de la commande go-debrid -l j'ai la demande d'authentification, j'ai tenté de me logger mais je me suis planté dans le mot de passe

puis j'ai retenté avec le bon user/mdp et la j'ai :

GetFormValues helper: No results for XPATH //form[@name="connectform"]

Une idée ?

**Comment by usineur** [comment]
supprime le fichier `~/.config/alldebrid/cookie.txt` et ré-essaye tes identifiants

**Comment by Amonbofils** [comment]
Alors ne fait le soucis venait du fait que je suis en russie actuellement et que normalement je suis en france, donc alldebrid demandait un code de vérification.

Par contre toujours impossible de me connecter toujours "invalid login/password?"

J'ai regardé, rien dans ~/.config/alldebrid/ ...

J'ai modifié mon mot de passe sur alldebrid, rien a faire

**Comment by usineur** [comment]
mmh oui tant que tu as le message "invalid login/password?" le fichier cookie.txt n'est pas créé, ça c'est normal.

Ce qui l'est moins, ce sont les raisons pour lesquelles tu n'arrives pas à t'identifier. Tu as un mot de passe avec des caractères spéciaux dedans ?

**Comment by usineur** [comment]
As-tu les droits d'écriture dans `~/.config` ou `~/.config/alldebrid` ?

D'ailleurs le dossier "alldebrid" est-il présent dans `~/.config` ?

Edit: si tu executes la commande "touch plop" dans `~/.config/alldebrid`, le fichier "plop" apparait-il dans ce dossier ?

**Comment by Amonbofils** [comment]
non

j'ai fait un test avec un mot de passe simple sans caractères accentués ni majuscule ou autre ...

Un reboot et je retente, sait-on jamais avec le nombre de bidouilles effectuées pour faire marche go ...

**Comment by Amonbofils** [comment]
pour les droits d'acces j'y ai pensé, j'ai chmodé le dossier config et ses sous répertoires mais c'était pas mieux...

Mon nas est parti en force fsck donc va falloir attendre un peu pour la suite ... je reviens vers toi des que possible !

**Comment by usineur** [comment]
ok ça marche, la suite pour moi demain, la nuit me portera peut-être conseil

**Comment by Amonbofils** [comment]
Bon au final test avant de dormir : 

GetFormValues helper: No results for XPATH //form[@name="connectform"]

le retour du premier soucis ... je me connecte via mon pc en france en web : OK
je me connecte depuis la russie en web : OK
je teste avec le NAS , bim message d'erreur ...

La je vois plus ...

**Comment by usineur** [comment]
Ton NAS est sur le même réseau que ton pc en France ? Là, j'avoue que je sèche, il est possible qu'il y ait un cas de connexion que je ne connais pas...

Faudrait que je te fasse une version qui logge ce qu'il se passe en détail quand tu essayes de te connecter... Si tu es ok, je t'enverrai un binaire pour ça

**Comment by Amonbofils** [comment]
Oui mon nas est bien sûr le même réseau que mon pc.

J'avoue ne pas comprendre non plus. Je vais retenter une installation de
ton plug-in au complet et voir ce qu'il advient.

Pour le bin modifié oui je veux bien mais il me faudra une méthode pour le
mettre en place, je rappelle que c'est la première fois que j'utilise go
Le 15 juin 2016 11:28 AM, "Matthieu Milan" notifications@github.com a
écrit :

**Comment by usineur** [comment]
Ok, essaye avec cette version pré-compilée: [https://www.ferb.fr/go-debrid.zip](https://www.ferb.fr/go-debrid.zip)

Et envoye moi les logs: `./go-debrid -l > output.txt`

Si tes identifants apparaissent dans le log, remplace la ligne
`eff: https://alldebrid.com/register/?action=login&login_login=pouet&login_password=pouet`
par
`eff: https://alldebrid.com/register/?action=login&login_login=****&login_password=****`

**Comment by Amonbofils** [comment]
j'ai obtenu ca :

./go-debrid: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by ./go-debrid)

rien dans le txt

**Comment by Amonbofils** [comment]
Alors cette erreur viens du fait qu'il me faut libc6 en v2.14 minimum, mais malheureusement sur wheezy, il n'y a que la v2.13...

et impossible de passer en version supérieure sans bouziller mon nas ...

Je n'avais pas cela avant, cela viendrait-il de ta version précompilée ?

**Comment by usineur** [comment]
Ça vient de ça en effet... J'essayerai de te fournir une version statique du binaire ou alors un patch à appliquer et tu n'auras qu'à recompiler.

**Comment by usineur** [comment]
Re, bon, essaye d'appliquer ce patch: [https://ferb.fr/debug.patch](https://ferb.fr/debug.patch) une fois les sources de go-debrid récupérées sur ton poste.

Pour compiler depuis les sources, il te suffit de te mettre à la racine de go-debrid et de taper `go get` une fois le patch appliqué.

**Comment by Amonbofils** [comment]
je sui vraiment navré, mais comment patcher ?

Je suis vraiment noob dans ce domaine ...

**Comment by usineur** [comment]
`patch -p1 < debug.patch` à la racine des sources

**Comment by Amonbofils** [comment]
alors dans l'ordre j'ai :
- Telechargé les sources
- Mis le patch dans le meme dossier
- Lancé le `patch -p1 <debug.patch`
- Lancé le `go get`
- lancé la commande go-debrid -l

résultat :
`GetFormValues helper: No results for XPATH //form[@name="connectform"]`

le fichier de sortie donne juste :
`**********`

**Comment by usineur** [comment]
euh ah ouais, alors là, c'est juste pas normal. Tu devrais avoir une sortie avec du code HTML. Là, j'avoue je sèche, mais alors totalement...

**Comment by usineur** [comment]
t'as essayé ton PC plutôt que ton NAS d'ailleurs ? Je sais pas, y a peut-être un élément de config du NAS qui fait que ça bloque go-debrid

**Comment by Amonbofils** [comment]
non j'ai pas essayé...

Je vais tenter en jessie, le but étant d'automatiser mes DL, seul mon  nas peux le faire ...

**Comment by usineur** [comment]
attends, es-tu sûr d'avoir utilisé le bon binaire ? En relisant, j'ai l'impression que l'output `**********` correspond à la saisie du mdp.

dans le doute, essaye `go build` plutôt que `go get`. Ca va te générer un binaire à la racine de go-debrid.
A lancer avec `./go-debrid -l`. Le `./` est très important ici

**Comment by Amonbofils** [comment]
OK !

Alors y'a du nouveau ... Pour faire court, ayant mon nas en france et mon pc en russie, je recevais 1 mail par connexion pour me dire que mon compte etait peut etre piraté

Comclusion j'ai coché la case "desactiver la geolocalisation" sur mon compte alldebrid

apres l'avoir remis comme a l'original, je retombe sur le premier probleme a savoir plus de message d'erreur mais par contre impossible de rentrer mon mot de passe "login/password invalid"

Cela pourrait-il venir de l’encodage de caracteres ?

**Comment by usineur** [comment]
avec la version patchée, tu devrais des logs en plus. Regarde mon avant-dernier commentaire, si tu ne l'as pas vu.

Et oui, il est possible que ça vient du greffon que j'utilise pour le mdp. Une piste a investiguer peut-être

**Comment by Amonbofils** [comment]
Tu veux dire celui a utiliser sur pc ?

Par contre, y'a encore et toujours du nouveau.. je me met donc a recevoir de nouveau un email pour m'informer d'un piratage possible.

J'ouvre alldebrid depuis mon pc france : code de vérification demandé ??? ok je tape le code recu par mail, ca a l'air de marcher! Je retourne sur mon nas, je relance la commande , et voila le retour du 

`Password: GetFormValues helper: No results for XPATH //form[@name="connectform"]`

rien a faire ca passe toujours pas ...

Pour info le patch est bien appliqué puisque qaudn je le relance il me dit qu'il existe deja ...

COmment on fait pour faire tourner ton script sur windaube ?

Accessiorement, il a été testé dans quel environement ton script ?

**Comment by usineur** [comment]
Essaye la version patchée sur ton PC perso déjà, ensuite, on regardera pour le NAS. Le code de vérification est demandée qu'il y a eu beaucoup de tentatives de connexion (ratées notamment), mais là je pense que ça vient du fait que tu te jongles entre les connexions en Russie et France.

les services de AllDebrid doivent détecter ça comme une activée suspecte (enfin... inhabituelle plutôt)

**Comment by Amonbofils** [comment]
Bon, apres avoir installé golang sur mon pc, je n'arrive pas a le faire tourner ... 

j'ai des erreur a la compilation : cannot find package ...

Bref, je pense que je t'ai assez fait perdre de temps comme ca...

**Comment by usineur** [comment]
J'ai fourni une version pré-compilée pour Windows: https://github.com/usineur/go-debrid/releases/tag/20160316
A voir si ça passe ou pas. De mémoire, il vaut mieux utiliser la console Windows, que des trucs exotiques comme MSYS2 ou cygwin.

Mon soft a été testé sous Linux (Fedora, Debian) et Windows 7. Peut être d'autres, j'ai eu des retours positifs d'utilisateurs, mais je ne connais pas toujours l'environnement qu'ils ont utilisés.

**Comment by Amonbofils** [comment]
Ton debian c'est un  Jessie ?
Le 18 juin 2016 12:52 PM, "Matthieu Milan" notifications@github.com a
écrit :

**Comment by usineur** [comment]
Wheezy... Pas la mienne, mais celui d'un utilisateur. Il rencontrait un bug, c'est corrigé depuis et tout marche bien pour lui.

**Comment by Amonbofils** [comment]
Après un long temps d'attente, me revoici ! et depuis la france uniquement !!! :dancers: 

Et ton script sur windows fonctionne !

je viens de tester sur mon nas et toujours rien ...

je vais tenter sur une autre machine (mon debian a souffert depuis des années de mes différentes manipulations ...) et je te redis, mais si tu as une idée je suis preneur !

Au cas ou, l'encodage des caractères peut-il etre en cause ?

**Comment by Amonbofils** [comment]
bon vérif faite sur un autre debian ... meme punition !

Je vais faire une install fraiche d'un debian jessy et on va voir ...

**Comment by Amonbofils** [comment]
AHHH bah y'a du mieux ! 

Alors sur un debian 8, l'install de golang seule et des paquets necessaires, et ca marche !
les points de différences sont : 
- Debian 7 = en francais / go v1.6 / fr_FR.UTF-8
- Debian 8 = En anglais / go v1.3.3 / en_US.UTF-8

Je vais donc essayer de basculer mon go en v1.3.3 pour tester ... Si ca marche pas, je tenterai avec un debian 7 propre en anglais pour voir ...

Edit : debian 7 go v1.3.3 = marche pas .... reste plus qu'a refaire une install propre en anglais ...

**Comment by usineur** [comment]
Salut, je me sers de go-debrid sur des envs "fr" ou "en" sans problèmes, je pense pas que ce soit un soucis de localisation... Pour la version de go, du moment que t'es > 1.1, c'est tout bon. L'encodage de caractères ne devrait lui aussi ne pas poser de souci...

Il me faudrait - dans l'absolu - une VM avec un sorte de ghost de ton env pour voir où se situe le problème, car pour moi, c'est un problème plus bas (config ? version des libs ? ...)

Désolé de ne pouvoir plus t'aider. N'hésiste pas à revenir vers moi quand t'auras réussi à lancer la bête sur ton NAS, ça me ferait plaisir de savoir que t'es enfin arrivé au bout de tes galères.

**Comment by Amonbofils** [comment]
t'inquiete je continu a fouiller ! 

Pour ma machine, je reteste en mode RAZ, je pars d'un iso de openmediavault en debian 7 et j'essai de rajouter tes scripts ! si tu veux faire l'essai, l'install est simple et prends 10min a peine sur une VM

**Comment by Amonbofils** [comment]
Bon, j'ai essayé de nouveau : 

Installation propre de OMV, en_US, X64:
https://sourceforge.net/projects/openmediavault/files/

 j'install juste 
apt-get install libcurl4-openssl-dev
apt-get install libxml2-dev
apt-get install gcc
apt-get install git

Et bien sur go en v>1.1 (dans mon cas sur cette machine 1.4.2)

et au lancement : 
GetFormValues helper: No results for XPATH //form[@name="connectform"]

donc toujours pas mieux ... Je vais tenter encore une fois sur un debian 7 sans openmediavault pour voir

En tout cas, si tu veux tester de ton coté, tu as ma config ...

**Comment by usineur** [comment]
ah super, je testerai ça dès que possible... à mon retour de congés déjà :-)

**Comment by usineur** [comment]
re, je viens de pousser une modif qui, je l'espère, corrigera ton souci. Dès que tu as un moment, si tu peux tester, dis moi ce qu'il en ait.

**Comment by Amonbofils** [comment]
quand je fais go get j'ai :

import /root/go/pkg/linux_amd64/github.com/usineur/go-debrid/alldebrid.a: object is [linux amd64 go1.6.2 X:none] expected [linux amd64 go1.3.3 X:precisestack]

ca viens de toi ou de moi ?

**Comment by usineur** [comment]
pas de moi, je ne commite que les sources, essaye de virer  alldebrid.a et recommence

en fait, je virerai presque le contenu de pkg pour peu que ton GOROOT et ton GOPATH soient différents

**Comment by usineur** [comment]
re, tu as pu t'en sortir alors ?

**Comment by Amonbofils** [comment]
Désolé j'ai pas encore eu le temps de m'en occuper, mais ce soir c'est les
vacances ! Donc plein de temps à consacrer à mes projets personnels !

Je te redis des que possible !

Le 28 juil. 2016 2:26 PM, "Matthieu Milan" notifications@github.com a
écrit :

**Comment by Amonbofils** [comment]
Me revoila !!!!!!!!!

Les vacannces sont finies alors j'ai du temps ! :D

Je viens de tester ta derniere version et ..... CA MARCHEEEEEEEE !!!!!!!!!! 

Par contre quand j'essai d'envoyer un fichier torrent il n'apparait pas dans la liste... je vais essayer de voir si je fait pas une connerie quelque part ... mais pour le moment ca marche pas :'(

**Comment by Amonbofils** [comment]
bon je viens de faire des essais mais ca ne marche pas ... 

je lance : 
 ./go-debrid -t /home/Downloads/Torrents/test.torrent

je recois bien :
/home/Downloads/Torrents/test.torrent correctly added to torrent queue

mais rien dans la file .... une idée ?

**Comment by usineur** [comment]
re,

déjà bonne nouvelle que tu puisses débrider maintenant.

ensuite pour le second soucis, j'ai activé le mode "verbose" pour investiguer. L'information la plus intéressante qui en ressort sont ces lignes:
`additional stuff not fine transfer.c:1037: 0 0`

qui semblent indiquer que la version de curl utilisée est buggée. Il faut que tu puisses mettre à jour la **libcurl** pour confirmer cette hypothèse.

**Comment by Amonbofils** [comment]
je viens de regarder, j'ai refais l'install mais apparemment j'ai la derniere version : 

libcurl4-gnutls-dev
libcurl4-nss-dev
libcurl4-openssl-dev_7.26.0-1+wheezy14_amd64.deb
curl_7.26.0-1+wheezy14_amd64.deb
libcurl3_7.26.0-1+wheezy14_amd64.deb

mais toujours rien ...

**Comment by usineur** [comment]
certe, mais cette version est loin d'être la dernière de curl. Si j'ai le temps, je verrais en buildant les sources de dernière release voir si ça résoud le problème

**Comment by Amonbofils** [comment]
j'ai fais une mise a jour vers la curl 7.50 mais toujours le meme résultat ...

Au cas ou, tu serais pas a la recherches d'améliorations a apporter a ton soft ? parceque j'en ai 2-3 en tete qui seraient pas mal... comme je ne sais pas coder en go, je peux pas le faire moi meme ... :D

**Comment by usineur** [comment]
> j'ai fais une mise a jour vers la curl 7.50 mais toujours le meme résultat ...

Ouaip, et je vois d'où vient le problème. Une histoire de redirection qui ne s'effectue pas correctement sur cet openmediavault de mes deux.
Le truc c'est que je ne vois pas du tout comment corriger ce problème... Je vais probablement devoir réécrire totalement la partie de code AddTorrent.

> Au cas ou, tu serais pas a la recherches d'améliorations a apporter a ton soft ? parceque j'en ai 2-3 en tete qui seraient pas mal... comme je ne sais pas coder en go, je peux pas le faire moi meme ... :D

pourquoi pas, mais pas dans cette "issue", créés en de nouvelles. Si ça me va, je m'y collerai... à mon rythme :)
