### ISSUE TITLE
Proposition d'améliorations

### ISSUE THREAD

**Issue by Amonbofils** [usineur/go-debrid#6]
Bonjour,

Comme convenu, voici une liste des idées que j'ai sur ce joli petit soft qui pourrait le rendre encore plus attractif !

1 - Choisir la localisation du download : en effet le -da lance le download dans le dossier du script. dans mon cas, c'est problématique puisque je suis sur un nas, le script s'execute sur le disque systeme (32Go) et donc un DL de gros fichier prends vite la place restante ...

2 - lors de l'utilisation du -da, induire le débridage automatique du lien, aujourd'hui ca dl le lien uptobox, 

3 - Ajouter une option "delete from list after download" Quand on fait un -da, le fichier se télécharge mais reste dans la liste des torrents de alldebrid. Le problème est que si on veux automatiser les envois de .torrent, les downloads and co, faire un -da, suivi d'un -ra pourrait potentiellement virer les torrents en cours. Donc en gros, faire un -da, puis lorsque le premier fichier est terminé, le supprimer de la liste en utilisant son ID, puis passer au DL du second. etc..

4 - Ajouter l'intégration de jdownloader : Petit soft bien connu pour gérer les DL en cours, pouvoir faire pause, intégration de alldebrid, etc etc ... son utilisation aide grandement lorsque qu'on a de grandes files d'attente. une version est dispo en linux, et un API est disponible via my.jdwonloader me semble-t-il.

voilaaaaaaaaa :D 

Pour ma part j'essai d'intégrer ces modifs va un traitement bash linux, mais je pense que cela pourrait etre des options du soft en lui même. Voila, on sait jamais cela peux avoir un echo chez d'autres utilisateurs :D

**Comment by usineur** [comment]
Alors:
- 1 - en fait si le dossier d'emplacement du binaire est dans la variable d'environnment PATH, tu peux le lancer  `go-debrid` de n'importe où et le lien à débrider sera téléchargé dans le dossier courant.
  Mais l'idée de pouvoir préciser l'emplacement souhaité du téléchargement sans switcher d'un dossier à un autre est intéressante. Je suis **OK** pour ajouter cette option.
- 2 - je ne vois pas ce que tu veux dire, l'option `-da` débride l'ensemble des liens uptobox, pour peu que la conversion du torrent en lien uptobox soit prête.
- 3 - **OK** pour cette option, elle peut s'avérer utile en effet.
- 4 - je ne connais du tout jDownloader, et il me semble qu'il existe déjà ce qu'il faut comme greffon pour AllDebrid, non ?

**Comment by Amonbofils** [comment]
Pour le point 2 , quand j'ai fait un -da, j'ai vu le download se lancer avec l'adresse uptobox et pas alldebrid... Alors j'ai supposé que le lien était pas débridé.

Pour le point 4. Jdownloader est un gestionnaire de téléchargement de lien direct ou HTTP. Sa gestion est plutôt bien foutu avec des priorité de download, la pause et reprise, gestion du débit alloué sur la bande passante, décompression des archives en automatique, gestion des capcha, planification horaire pour les DL etc etc ... C'est un gestionnaire de DL très utilisé, et franchement qui facilite bien la vie. Du coup je me demandait si c'était possible ou pas :D

Imagine que tu met 15 liens torrrent dans alldebrid et que que tu fais un -da. Bon ca se lance, pas de soucis, mais d'un coup, tu as besoin de la bande passante pour skyper, uploader un fichier ou lancer un download plus urgent. bah c'est quand meme plus simple avec un gestionnaire de download avec une interface graphique que de passer par la console ...

**Comment by usineur** [comment]
C'est ça qu'il te faut alors: [AllDebrid: Plugin Jdownloader](https://alldebrid.fr/jdownloader/). Non ?

_go-debrid_ est une alternative en ligne de commande. C'est une solution pour ceux qui lanceraient leurs téléchargements depuis un serveur sans interface graphique. Ou pour les accros de la console.
Je ne compte pas me lancer dans des développements qui sortiraient de ce cadre.
