### ISSUE TITLE
panic:runtime error

### ISSUE THREAD

**Issue by Amonbofils** [usineur/go-debrid#7]
Salutations !

je reviens de nouveau vers toi pour un nouveau soucis... d'un coup d'un seul, le script est parti en sucette. Je ne comprends pas pkoi.

###Result
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4a595b]

goroutine 1 [running]:
panic(0x624580, 0xc4200100e0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/usineur/goch.GetTableDataAsArrayWithHeaders(0xc4203dd000, 0x49eb, 0x669e1d, 0x16, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
        /root/go/src/github.com/usineur/goch/helper.go:167 +0x6ab
github.com/usineur/go-debrid/alldebrid.Torrent(0xc4200628a0, 0x1, 0x1, 0x16, 0x1)
        /root/go/src/github.com/usineur/go-debrid/alldebrid/torrent.go:47 +0x11f
github.com/usineur/go-debrid/alldebrid.Torrent(0xc4200628a0, 0x1, 0x1, 0x22, 0x4148ac)
        /root/go/src/github.com/usineur/go-debrid/alldebrid/torrent.go:45 +0xe1e
main.main.func2(0x7ffdcbc1fe56, 0x2)
        /root/go/src/github.com/usineur/go-debrid/main.go:20 +0x57
main.main()
        /root/go/src/github.com/usineur/go-debrid/main.go:86 +0x92
```

J'ai viré compelment go, reinstaller tout go + go-debrid, rien n'y fait.

Aurais-tu une idée ?

merci d'avance.

**Comment by Amonbofils** [comment]
Bon bah j'ai fini par tout virer, recommencer en utilisant le paquet de golang et s'est passé...

par contre pendant ce temps j'ai codé a la main de quoi faire a peu pres la meme chose mais en php.

Le seul soucis que je rencontre c'est que je ne sais pas comment envoyer un fichier .torrent à alldebrid. Tu penses que tu pourrais m'aider sur le sujet ? je sais que c'est du cURL mais je vois pas comment faire ...

**Comment by usineur** [comment]
Salut,

J'adore les problèmes qui se ressoudent sans que je n'ai rien à faire :)

Pour les torrents, il faut envoyer une Form vers l'URL suivante: http://upload.alldebrid.com/uploadtorrent.php

Tu trouveras un exemple d'utilisation en PHP ici: https://github.com/wzul/Alldebrid-System/blob/master/fileupload.php

Les informations à mettre dans le Form sont données dans cet exemple.
