### ISSUE TITLE
Ajout impossible

### ISSUE THREAD

**Issue by Amonbofils** [usineur/go-debrid#9]
Bonjour,

Depuis quelque temps, impossible d'envoyer un torrent a alldebrid... Je viens d'upgrader ma version de go, et j'ai mis a jour go-debrid, mais rien a faire : 

 go/bin/./go-debrid -t test.torrent

le retour est bon : 

test.torrent correctly added to torrent queue

et pourtant rien sur alldebrid ... une idée ?
go version :  go version go1.11.1 linux/amd64

**Comment by usineur** [comment]
Salut,

Je miserai sur un changement d'API (encore). Enfin probablement...
N'ayant plus d'abonnement à Alldebrid, je vais avoir du mal à investiguer . Si je me décide à reprendre un abonnement, je jetterai un oeil.

**Comment by Amonbofils** [comment]
si je t'offre un mois de alldebrid ? c'est jouable ?

**Comment by usineur** [comment]
C'est gentil, mais pas besoin. J'ai finalement tranché ce week-end et j'ai repris un abo.

Pas eu le temps de regarder cependant. Je pense m'y replonger courant de semaine prochaine.
Je te tiens au courant.

**Comment by Amonbofils** [comment]
De ce que j'ai pu tester avec postman, y'a une demande de capcha, je sais pas si je m'y suis mal pris avec les cookies ou autre... En tout cas ça peut être une piste !

Redis moi si je peux aider

**Comment by usineur** [comment]
Ah ok je vois.

go-debrid ne gère absolument pas ce captcha que Alldebrid demande parfois (nouvelle IP, changement de zone géographique, ...)

Le seul moyen de se connecter alors est de passer au moins une fois par le site officiel depuis la même IP où tu vas utiliser go-debrid.

Et si au pire ça ne fonctionne pas - je vois pas de raison, mais bon - il faut utiliser un plugin chrome/firefox comme EditThisCookie et mettre (une fois connecté depuis le web) les bonnes valeurs des clefs `uid` et `__cfduid` dans `~/.config/alldebrid/cookie.txt`

**Comment by usineur** [comment]
Je viens d'y penser: j'ai oublié de préciser qu'il n'y a eu de changement d'API dernièrement.
J'arrive à ajouter/supprimer les torrents sans problème depuis le "correctif" mis en place au commit 49d33c1

**Comment by Amonbofils** [comment]
Il est où le fichier cookies ? Je vais le supprimer pour en recréer un !

**Comment by usineur** [comment]
Je l'ai indiqué dans mon avant dernier message

**Comment by Amonbofils** [comment]
bon je viens de rentrer chez moi, et j'ai beau essayer, rien n'y fait... j'ai viré le fichier cookies, recréé un nouveau , rechangé manuellement le fichier avec les valeurs obtenues dans la console de chrome... que dalle :D 

y'a moyen de connaitre la version de go-debrid installée ? sur quel commit on est ?

**Comment by usineur** [comment]
Pas vraiment... Il y a juste à faire `go get github.com/usineur/go-debrid` et ça compile la dernière version normalement. Le binaire est généré dans $GOPATH/bin

Après, je vois pas vraiment ce qui peut clocher pour être honnête.
